version: "3"
services:
  web:
    build: ./
    env_file: &envfile
      - env.env
    command: >
      bash -c "python3 dev_manage.py migrate
      && python3 dev_manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
      - ./galaxiaweb/static/:/static/
      - ./files/:/code/files/
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3
    env_file: *envfile
    ports:
      - "5671:5671"

  celery:
    build: ./
    restart: "no"
    env_file: *envfile
    command: celery -A galaxiaui worker -l info
    volumes:
      - ./:/code
    depends_on:
      - rabbitmq
