version: "3"
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    env_file: &envfile
      - env.prod
    command: >
      bash -c "dockerize -wait tcp://db:3306 -timeout 360s -wait-retry-interval 5s
      && mkdir -p galaxiaui/logs
      && python3 manage.py migrate
      && python3 manage.py collectstatic --noinput
      && gunicorn galaxiaui.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./galaxiaweb/static/:/static/
      - media_files:/code/files/
    expose:
      - 8000
    depends_on:
      - rabbitmq
      - db

  rabbitmq:
    image: rabbitmq:3
    env_file: *envfile
    ports:
      - "5671:5672"
  celery:
    build:
      context: ./
      dockerfile: Dockerfile.celery
    restart: "no"
    env_file: *envfile
    command: celery -A galaxiaui worker -l info
    volumes:
      - ./galaxiaweb/static/:/static/
      - media_files:/code/files/
    depends_on:
      - rabbitmq
      - web
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
  db:
    image: mysql:5.7
    env_file: *envfile
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
volumes:
  media_files:
  db_data: