version: "3"
services:
  web:
    build: ./
    env_file: &envfile
      - env.env
    command: >
      bash -c "mkdir -p log
      && python3 dev_manage.py migrate
      && python3 dev_manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
      - ./galaxiaweb/static/:/static/
      - ./files/:/files/
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq

#  galaxia:
#    build: ./
#    command: >
#      bash -c " cd /code/galaxia
#                && tar -zxvf galaxia-0.8.1.tar.gz
#                && cd galaxia-0.8.1
#                && ./configure --datadir=/GalaxiaData
#                && make
#                && make install
#                && cp -r GalaxiaData /
#                && cd /code/galaxia
#                && tar -zxvf ebfpy-0.0.14.tar.gz
#                && cd ebfpy-0.0.14
#                && python setup.py install --install-scripts=/bin/
#                && echo Y | galaxia -s warp
#                && rmdir /code/galaxia/galaxia-0.8.1"
#    depends_on:
#      - web

  rabbitmq:
    image: rabbitmq:3
    env_file: *envfile
    ports:
      - "5671:5671"

  celery:
    build: ./
    restart: "no"
    env_file: *envfile
    command: celery -A galaxiaui worker -l info
    volumes:
      - ./:/code
    depends_on:
      - rabbitmq