# Generated by Django 2.1.7 on 2019-03-29 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_file', models.CharField(choices=[('Sharma 2011', 'Sharma 2011'), ('Sharma 2019', 'Sharma 2019')], default='Sharma 2019', max_length=55)),
                ('apparent_magnitude_min', models.FloatField(default=-100.0)),
                ('apparent_magnitude_max', models.FloatField(default=14.0)),
            ],
        ),
    ]
