# Generated by Django 2.1.7 on 2019-04-15 09:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('galaxiaweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobparameter',
            name='job_key',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
