# Generated by Django 2.1.7 on 2019-03-29 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxiaweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobparameter',
            name='photo_sys_1',
            field=models.CharField(choices=[('parsec1', 'parsec1')], default='parsec1', max_length=20),
        ),
    ]
