# Generated by Django 2.1.7 on 2019-05-09 02:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxiaweb', '0002_jobparameter_job_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobparameter',
            name='latitude',
            field=models.FloatField(default=90, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='jobparameter',
            name='longitude',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)]),
        ),
        migrations.AlterField(
            model_name='jobparameter',
            name='r_max',
            field=models.FloatField(default=1000, validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='jobparameter',
            name='sample_fraction',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='jobparameter',
            name='seed',
            field=models.PositiveIntegerField(default=17, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='jobparameter',
            name='survey_area',
            field=models.FloatField(default=100, validators=[django.core.validators.MaxValueValidator(41252)]),
        ),
    ]
