# Generated by Django 2.1.7 on 2019-06-19 06:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxiaweb', '0003_auto_20190509_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobparameter',
            name='email',
            field=models.CharField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AddField(
            model_name='jobparameter',
            name='parameter_file_url',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobparameter',
            name='parameters',
            field=models.BinaryField(default=None, null=True),
        ),
    ]
