# Generated by Django 2.1.7 on 2019-04-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxiaweb', '0003_jobparameter_photo_sys_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobparameter',
            name='absolute_magnitude_max',
            field=models.FloatField(default=14.0),
        ),
        migrations.AddField(
            model_name='jobparameter',
            name='absolute_magnitude_min',
            field=models.FloatField(default=-100.0),
        ),
    ]
