# Generated by Django 2.1.7 on 2019-04-04 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxiaweb', '0006_auto_20190404_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobparameter',
            name='geometry_options',
            field=models.CharField(choices=[('All Sky', 'All Sky'), ('Circular Patch', 'Circular Patch')], default='All Sky', max_length=55),
        ),
        migrations.AddField(
            model_name='jobparameter',
            name='magnitude_name',
            field=models.CharField(choices=[('Placeholder', 'Placeholder')], default='Placeholder', max_length=55),
        ),
    ]
