# Generated by Django 2.1.7 on 2019-04-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxiaweb', '0007_auto_20190404_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobparameter',
            name='latitude',
            field=models.FloatField(default=90),
        ),
        migrations.AddField(
            model_name='jobparameter',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='jobparameter',
            name='population_ID',
            field=models.CharField(choices=[('All thin/thick disk, halo and bulge populations', 'All thin/thick disk, halo and bulge populations'), ('Thin Disk <0.15 Gyr', 'Thin Disk <0.15 Gyr'), ('Thin Disk  0.15-1 Gyr', 'Thin Disk  0.15-1 Gyr'), ('Thin Disk  1-2 Gyr', 'Thin Disk  1-2 Gyr'), ('Thin Disk  2-3 Gyr', 'Thin Disk  2-3 Gyr'), ('Thin Disk  3-5 Gyr', 'Thin Disk  3-5 Gyr'), ('Thin Disk  5-7 Gyr', 'Thin Disk  5-7 Gyr'), ('Thin Disk  7-10 Gyr', 'Thin Disk  7-10 Gyr'), ('Thick Disk', 'Thick Disk'), ('Stellar Halo', 'Stellar Halo'), ('Bulge', 'Bulge'), ('Bullock & Johnston stellar halos', 'Bullock & Johnston stellar halos')], default='All thin/thick disk, halo and bulge populations', max_length=55),
        ),
        migrations.AddField(
            model_name='jobparameter',
            name='r_max',
            field=models.FloatField(default=1000),
        ),
        migrations.AddField(
            model_name='jobparameter',
            name='sample_fraction',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='jobparameter',
            name='seed',
            field=models.PositiveIntegerField(default=17),
        ),
        migrations.AddField(
            model_name='jobparameter',
            name='survey_area',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='jobparameter',
            name='warp_flare',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
