# Generated by Django 2.1.7 on 2019-04-08 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galaxiaweb', '0008_auto_20190404_0504'),
        ('galaxiaweb', '0004_auto_20190403_0137'),
    ]

    operations = [
    ]
