# Generated by Django 2.1.7 on 2019-04-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxiaweb', '0009_merge_20190408_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobparameter',
            name='absolute_magnitude_max',
            field=models.FloatField(default=100.0),
        ),
    ]
